version: "3.3"
services:
  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      - .:/code
    environment:
      DATABASE_NAME: 'smallbrains_dev'
      DATABASE_TEST_NAME: 'smallbrains_test'
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: 'root'
      DATABASE_HOST: '127.0.0.1'
      DATABASE_PORT: '3306'
      SECRET_KEY: 'secret'
    networks:
      - smallbrain-net
  db:
    image: mysql:5.7
    ports:
      - 127.0.0.1:3306:3306
    environment:
      MYSQL_DATABASE: 'smallbrains_development'
      MYSQL_ROOT_PASSWORD: 'root'
    networks:
      - smallbrain-net
    command: [--ignore-db-dir=lost+found]
    volumes:
      - db-data:/var/lib/mysql/data
      - db-datadir:/var/lib/mysql

volumes:
  db-datadir:
  db-data:

networks:
  smallbrain-net:
