name: Django CI

on: [push]

env:
  SECRET_KEY: secret-key
  DATABASE_NAME: development
  DATABASE_TEST_NAME: test
  DATABASE_USER: root
  DATABASE_PASSWORD: root
  DATABASE_HOST: 127.0.0.1
  DATABASE_PORT: 3306

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7]
        node-version: [12.22]

    steps:
    - uses: actions/checkout@v2

    - name: Install Mysql client 
      run: | 
        sudo apt-get install default-libmysqlclient-dev build-essential
        sudo wget https://raw.githubusercontent.com/paulfitz/mysql-connector-c/master/include/my_config.h -P /usr/include/mysql/

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up Node ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Python Dependencies
      run: |
        pip install pathlib
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Node Dependencies
      run: |
        npm install static/

    - name: Run Mysql Container
      run: |
        sudo docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=root -p 3306:3306 mysql:5.7.22 --sql_mode=""
        
    - name: Run migrations
      run: |
        python manage.py migrate

    - name: Run Tests
      run: |
        python manage.py test test