name: Push docker image | Production

env:
  IMAGE: smallbrains
  
on:
  push:
    branches: [main]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set time
        run: |
          echo "date="$(date +"%Y-%m-%d")"" >> $GITHUB_ENV

      - name: Login to GAR
        uses: docker/login-action@v1
        with:
          registry: us-east4-docker.pkg.dev
          username: _json_key_base64
          password: ${{ secrets.GAR_JSON_KEY }}

      - name: Build image
        run: docker build -t "$IMAGE" .
    
      - name: Push image
        run: |
          docker tag "$IMAGE" us-east4-docker.pkg.dev/smallbrain-dev/smallbrains/andromeda:${{ env.date }}

          docker push us-east4-docker.pkg.dev/smallbrain-dev/smallbrains/andromeda:${{ env.date }}
